class NotFoundError(Exception):
    pass

class AlreadyInUseError(Exception):
    pass
